// React/src/components/vehicles/Details.tsx
import { useEffect, useState }    from 'react'
import { apiManager }             from '../../api/apiManager'
import type { Vehicle, Location } from '../../models'
import { getStatusColor }         from '../../utils/getStatusColor'

// ********** COMPONENTS **********
import {
  Typography,
  Box,
  Chip,
  Divider,
}                                                 from '@mui/material'
import { MapContainer, TileLayer, Marker, Popup } from 'react-leaflet'
import MapUpdater                                 from './../MapUpdater'
import L                                          from 'leaflet'

// ********** ICONS & ASSETS **********
import carImage     from '../../assets/Car.png'
import vanImage     from '../../assets/Van.png'
import truckImage   from '../../assets/Truck.png'
import carIcon      from '../../assets/icons/Car.png'
import vanIcon      from '../../assets/icons/Van.png'
import truckIcon    from '../../assets/icons/Truck.png'

const vehicleImages: Record<string, string> = {
  Car: carImage,
  Van: vanImage,
  Truck: truckImage,
}

const vehicleIcons: Record<string, L.Icon> = {
  Car: new L.Icon({
    iconUrl: carIcon,
    iconSize: [32, 24],
    iconAnchor: [16, 32],
    popupAnchor: [0, -32],
  }),
  Van: new L.Icon({
    iconUrl: vanIcon,
    iconSize: [32, 24],
    iconAnchor: [16, 32],
    popupAnchor: [0, -32],
  }),
  Truck: new L.Icon({
    iconUrl: truckIcon,
    iconSize: [32, 24],
    iconAnchor: [16, 32],
    popupAnchor: [0, -32],
  }),
}


// ********** MAP CONFIG **********
const center: [number, number] = [50.85, 4.35] // Bruxelles
const MAPBOX_TOKEN             = import.meta.env.VITE_MAPBOX_TOKEN


// ********** PROPS **********
type Props = { vehicle: Vehicle }


// ********** COMPONENT **********
const VehicleDetails = ({ vehicle }: Props) => {

  // ********** DATA **********
  const [location, setLocation] = useState<Location | null>(null)
  const statusColor             = getStatusColor(vehicle.status)


  // ********** EFFECTS **********
  useEffect(() => {
    // END measurement when map is loaded
    performance.mark('map-end')
    performance.measure('map-duration', 'map-start', 'map-end')

    const entries = performance.getEntriesByName('map-duration')
    const duration = entries[entries.length - 1]?.duration.toFixed(2)
    console.log(`🗺️ Map load duration: ${duration} ms`)

  }, [])

  useEffect(() => {
    const fetchLocation = () => {
      apiManager.location.getVehicleById(vehicle.id)
      .then((res) => setLocation(res.data))
      .catch(console.error)
    }
    fetchLocation()
    const intervalId = setInterval(fetchLocation, 3000)
    return () => clearInterval(intervalId)
  }, [vehicle.id])


  return (
    <Box sx={{ display: 'flex', gap: 4, flexDirection: { xs: 'column', md: 'row' } }}>

      <Box width={{ md: '30%' }}>

        {/* ******************** VEHICLE INFO ******************** */}
        <Typography variant="h6" fontWeight={600} gutterBottom>
          Vehicle Info
        </Typography>

        <img
          src={vehicleImages[vehicle.type] || truckImage}
          alt="Vehicle"
          style={{
            width: '100%',
            maxHeight: 160,
            objectFit: 'cover',
            borderRadius: 8,
            marginBottom: 16,
          }}
        />

        <Typography><strong>Brand:</strong> {vehicle.brand}</Typography>
        <Typography><strong>Model:</strong> {vehicle.model}</Typography>
        <Typography><strong>Type:</strong> {vehicle.type}</Typography>
        <Box sx={{ display: 'flex', alignItems: 'center', mt: 1 }}>
          <strong>Status:</strong>&nbsp;<Chip label={vehicle.status} color={statusColor} size="small" />
        </Box>
        
        {/* ***** LOCATION ***** */}
        <Typography sx={{ mt: 1 }}><strong>Last Location:</strong> Brussel</Typography>
        <Typography variant="body2" color="text.secondary">
          {location ? new Date(location.timestamp).toLocaleString() : 'N/A'}
        </Typography>
        

        <Divider sx={{ my: 2 }} />

        
        {/* ******************** VEHICLE INFO ******************** */}
        <Typography variant="h6" fontWeight={600} gutterBottom>
          Driver Info
        </Typography>

        {vehicle.currentDriver ? (
          <>
            <Typography><strong>Name:</strong> {vehicle.currentDriver.firstName} {vehicle.currentDriver.lastName}</Typography>
            <Typography><strong>Email:</strong> {vehicle.currentDriver.email}</Typography>
            <Typography><strong>Phone:</strong> {vehicle.currentDriver.phone}</Typography>
            <Typography><strong>Status:</strong> {vehicle.currentDriver.status}</Typography>
          </>
        ) : <em style={{ color: '#888' }}>Unassigned</em>}

      </Box>

      <Divider orientation="vertical" flexItem sx={{ display: { xs: 'none', md: 'block' } }} />

      {/* ******************** MAP ******************** */}
      <Box sx={{ flex: 1 }}>

        <Typography variant="h6" fontWeight={600} gutterBottom>
          Location
        </Typography>

        <MapContainer
          center={location ? [location.latitude, location.longitude] : center}
          zoom={12}
          style={{ height: '90%', width: '100%', borderRadius: 8 }}
        >
          <TileLayer
            url={`https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/{z}/{x}/{y}?access_token=${MAPBOX_TOKEN}`}
            attribution='© <a href="https://www.mapbox.com/">Mapbox</a>'
          />
          
          {location && (
            <>
              <MapUpdater position={[location.latitude, location.longitude]} />
              <Marker 
                position={[location.latitude, location.longitude]}
                icon={vehicleIcons[vehicle.type] || vehicleIcons['Truck']}
              >
                <Popup>{vehicle.licensePlate} – {vehicle.brand}</Popup>
              </Marker>
            </>
          )}
        </MapContainer>
      </Box>

    </Box>
  )
}

export default VehicleDetails

// Vue/src/components/vehicles/Details.vue
<template>
  <div class="d-flex flex-column flex-md-row ga-6">

    <!-- ********************** INFO ********************** -->
    <div style="width: 100%; max-width: 360px">

      <h3 class="text-h6 font-weight-bold mb-3">Vehicle Info</h3>

      <v-img
        :src="vehicleImages[vehicle.type] || defaultImage"
        height="160"
        cover
        class="mb-3 rounded"
      />

      <div><strong>Brand:</strong> {{ vehicle.brand }}</div>
      <div><strong>Model:</strong> {{ vehicle.model }}</div>
      <div><strong>Type:</strong> {{ vehicle.type }}</div>

      <div class="mt-2 d-flex align-center">
        <strong style="margin-right: 10px;">Status:</strong>
        <StatusChip :status="vehicle.status" />
      </div>

      <div class="mt-2"><strong>Last Location:</strong> Brussel</div>
      <div class="text-grey-darken-1">
        {{ location ? new Date(location.timestamp).toLocaleString() : 'N/A' }}
      </div>

      <v-divider class="my-4" />

      <!-- ********************** DRIVER INFO ********************** -->
      <h3 class="text-h6 font-weight-bold mb-3">Driver Info</h3>

      <template v-if="vehicle.currentDriver">
        <div><strong>Name:</strong> {{ vehicle.currentDriver.firstName }} {{ vehicle.currentDriver.lastName }}</div>
        <div><strong>Email:</strong> {{ vehicle.currentDriver.email }}</div>
        <div><strong>Phone:</strong> {{ vehicle.currentDriver.phone }}</div>
        <div><strong>Status:</strong> {{ vehicle.currentDriver.status }}</div>
      </template>
      <em v-else class="text-grey">Unassigned</em>

    </div>

    <v-divider vertical class="d-none d-md-block" />

    <!-- ********************** MAP ********************** -->
    <div class="flex-grow-1">

      <h3 class="text-h6 font-weight-bold mb-3">Location</h3>

      <div style="width: 100%; height: 500px; border-radius: 8px; overflow: hidden;">

        <LMap
          :center="mapCenter as [number, number]"
          :zoom="12"
          style="height: 100%; width: 100%;"
          ref="leafletMapRef"
        >
          <LTileLayer
            :url="tileUrl"
            :attribution="attribution"
          />
          <LMarker
            v-if="location"
            :lat-lng="[location.latitude, location.longitude]"
            :icon="icon"
          >
            <LPopup>
              {{ vehicle.licensePlate }} – {{ vehicle.brand }}
            </LPopup>
          </LMarker>
        </LMap>
        
      </div>

    </div>
    
  </div>
</template>


<!-- ********************** SCRIPT ********************** -->
<!-- ********************** SCRIPT ********************** -->
<script setup lang="ts">

  // ********** IMPORTS **********
  import { 
    ref, 
    onMounted, 
    onBeforeUnmount, 
    computed, 
    nextTick 
  }                                 from 'vue'
  import { API }                    from '@/api'
  import type { Vehicle, Location } from '@/models'


  // ********** COMPONENTS **********
  import 'leaflet/dist/leaflet.css'
  import { 
    LMap, 
    LTileLayer, 
    LMarker, 
    LPopup 
  }                                 from '@vue-leaflet/vue-leaflet'
  import L                          from 'leaflet'
  import StatusChip                 from '../shared/StatusChip.vue'


  // ********** PROPS **********
  const props = defineProps<{vehicle: Vehicle}>()

  // ********** MAP **********
  const defaultCenter: [number, number] = [50.85, 4.35]
  const tileUrl                         = `https://api.mapbox.com/styles/v1/mapbox/streets-v11/tiles/{z}/{x}/{y}?access_token=${import.meta.env.VITE_MAPBOX_TOKEN}`
  const attribution                     = '© <a href="https://www.mapbox.com/">Mapbox</a>'
  const leafletMapRef                   = ref<InstanceType<typeof LMap> | null>(null)
  const mapCenter                       = computed(() =>
    location.value ? [location.value.latitude, location.value.longitude] : defaultCenter
  )

  // ********** ICONS **********
  import carIcon    from '@/assets/icons/Car.png'
  import vanIcon    from '@/assets/icons/Van.png'
  import truckIcon  from '@/assets/icons/Truck.png'

  const vehicleIcons: Record<string, L.Icon> = {
    Car: L.icon({ iconUrl: carIcon, iconSize: [32, 24], iconAnchor: [16, 32], popupAnchor: [0, -32] }),
    Van: L.icon({ iconUrl: vanIcon, iconSize: [32, 24], iconAnchor: [16, 32], popupAnchor: [0, -32] }),
    Truck: L.icon({ iconUrl: truckIcon, iconSize: [32, 24], iconAnchor: [16, 32], popupAnchor: [0, -32] }),
  }
  const icon = computed(() => vehicleIcons[props.vehicle.type] || vehicleIcons.Truck)

  // ********** IMAGE **********
  import carImage     from '@/assets/Car.png'
  import vanImage     from '@/assets/Van.png'
  import truckImage   from '@/assets/Truck.png'

  const defaultImage = truckImage
  const vehicleImages: Record<string, string> = {
    Car:    carImage,
    Van:    vanImage,
    Truck:  truckImage
  }

  // ********** LOCATION FETCH **********
  const location = ref<Location | null>(null)
  let intervalId: number

  const fetchLocation = () => {
    API.location.getVehicleById(props.vehicle.id)
    .then((res) => location.value = res.data)
    .catch(console.error)
  }

  
  // ********** HOOKS **********
  onMounted(() => {
    fetchLocation()
    intervalId = setInterval(fetchLocation, 3000)

    const map = leafletMapRef.value?.leafletObject as L.Map
    map?.invalidateSize()

    // End performance measurement for map load
    performance.mark('map-end')
    performance.measure('map-duration', 'map-start', 'map-end')

    const entries = performance.getEntriesByName('map-duration')
    const duration = entries[entries.length - 1]?.duration.toFixed(2)
    console.log(`🗺️ Map load duration: ${duration} ms`)
    
  })

  onBeforeUnmount(() => {
    clearInterval(intervalId)
  })
  
</script>
