// React/src/pages/dashboard.tsx
// ********** COMPONENTS **********
import {
  Box,
  Typography,
}                           from '@mui/material'
import DashboardMap         from '../components/dashboard/Map'
import DashboardAlerts      from '../components/dashboard/Alerts'
import ActiveVehiclesChart  from '../components/dashboard/charts/ActiveVehicles'
import VehicleStatusPie     from '../components/dashboard/charts/VehiclesStatus'
import KPICards             from '../components/dashboard/KPICards'

const DashboardPage = () => {

  return (
    <>
      {/* ********** TITLE ********** */}
      <Typography variant="h4" fontWeight={600} gutterBottom>
        Dashboard
      </Typography>


      {/* ********** KPI CARDS ********** */}
      <KPICards />


      {/* ********** DASHBOARD CONTENT ********** */}
      <Box
        sx={{
          display: 'flex',
          flexDirection: { xs: 'column', md: 'row' },
          gap: 3,
        }}
      >

        {/* ********** LEFT PANEL ********** */}
        <Box flex={1}>

          {/* ***** ACTIVE VEHICLES CHART ***** */}
          <ActiveVehiclesChart />

          {/* ***** VEHICLE STATUS PIE ***** */}
          <VehicleStatusPie />

        </Box>


        {/* ********** RIGHT PANEL ********** */}
        <Box flex={1}>

          {/* ***** ALERTS ***** */}
          <DashboardAlerts />

          {/* ***** MAP ***** */}
          <DashboardMap />

        </Box>

      </Box>
    </>
  )
}

export default DashboardPage

// Vue/src/views/Dashboard.vue
<template>
  <div>

    <!-- ********************** TITLE ********************** -->
    <h1 class="text-h4 font-weight-bold mb-6">Dashboard</h1>

    <!-- ********************** KPI CARDS ********************** -->
    <KPICards />

    
    <!-- ********************** DASHBOARD CONTENT ********************** -->
    <div class="d-flex flex-column flex-md-row ga-3">

      <!-- ********** LEFT PANEL ********** -->
      <div class="d-flex flex-column" style="flex: 1 1 0">
        <!-- ACTIVE VEHICLES CHART -->
        <ActiveVehicles />

        <!-- VEHICLE STATUS PIE -->
        <VehicleStatusPie />
      </div>

      <!-- ********** RIGHT PANEL ********** -->
      <div class="d-flex flex-column" style="flex: 1 1 0">
        <!-- ALERTS -->
        <Alerts />

        <!-- MAP -->
        <Map />
      </div>

    </div>

  </div>
</template>


<!-- ********************** SCRIPT ********************** -->
<!-- ********************** SCRIPT ********************** -->
<script setup lang="ts">

  // ********** IMPORTS **********
  import KPICards         from '@/components/dashboard/KPICards.vue'
  import ActiveVehicles   from '@/components/dashboard/charts/ActiveVehicles.vue';
  import VehicleStatusPie from '@/components/dashboard/charts/VehicleStatusPie.vue';
  import Alerts           from '@/components/dashboard/Alerts.vue';
  import Map              from '@/components/dashboard/Map.vue';

</script>
