// Vue/src/components/shared/KPIBar.vue
<template>

  <!-- ********************** KPI BAR ********************** -->
  <v-sheet
    elevation="4"
    class="d-flex flex-wrap justify-space-evenly align-center pa-4 mb-6 text-body-2"
  >
    <!-- ************** ITEMS ************** -->
    <div
      v-for="item in items"
      :key="item.label"
      class="d-flex align-center"
      style="gap: 8px"
    >
      <!-- ***** COLOR ***** -->
      <div
        :style="{
          width: '10px',
          height: '10px',
          borderRadius: '50%',
          backgroundColor: item.color,
        }"
      />

      <!-- ***** VALUE ***** -->
      <span style="opacity: 0.7">{{ item.count }}</span>

      <!-- ***** LABEL ***** -->
      <span style="font-weight: 500">{{ item.label }}</span>
    </div>
  </v-sheet>

</template>

<script setup lang="ts">

  // ********** PROPS **********
  defineProps<{
    items: {
      label: string
      count: number
      color: string
    }[]
  }>()

</script>

// React/src/components/shared/KPIBar.tsx
// ********** COMPONENTS **********
import { Box, Typography, Paper } from '@mui/material'


// ********** PROPS **********
type KPIItem = {
  label: string
  count: number
  color: string
}

type KPIBarProps = {
  items: KPIItem[]
}


// ********** COMPONENT **********
const KPIBar = ({ items }: KPIBarProps) => {

  return (
    // ********** KPI BAR **********
    <Paper
      sx={{
        display: 'flex',
        justifyContent: 'space-evenly',
        p: 2,
        mb: 3,
        flexWrap: 'wrap',
        alignItems: 'center',
        fontSize: 15,
      }}
      elevation={4}
    >
      {/* ******* ITEMS ******* */}
      {items.map(({ label, count, color }) => (
        <Box key={label} sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          
          {/* ***** COLOR ***** */}
          <Box
            sx={{
              width: 10,
              height: 10,
              borderRadius: '50%',
              backgroundColor: color,
            }}
          />
          
          {/* ***** VALUE ***** */}
          <Typography variant="body2" sx={{ opacity: 0.7 }}>
            {count}
          </Typography>
          
          {/* ***** LABEL ***** */}
          <Typography variant="body2" sx={{ fontWeight: 500 }}>
            {label}
          </Typography>

        </Box>
      ))}
    </Paper>
  )
}

export default KPIBar
