// Vue/src/components/drivers/Details.vue
<template>
  <div class="d-flex flex-column flex-sm-row ga-6">
    
    <!-- ********************** LEFT PANEL ********************** -->
    <div class="d-flex align-center ga-4" style="min-width: 340px;">

      <!-- ***** AVTAR ***** -->
      <v-avatar :image="Avatar" size="100" rounded="lg" />

      <!-- ***** INFO ***** -->
      <div class="d-flex flex-column ga-2 text-body-2">
        <div><strong>Email:</strong> {{ driver.email }}</div>
        <div><strong>Phone:</strong> {{ driver.phone }}</div>
        <div class="d-flex align-center">
          <strong style="margin-right: 10px;">Status:</strong>
          <StatusChip :status="driver.status" />
        </div>
      </div>

    </div>

    <v-divider vertical class="d-none d-md-block" />

    <!-- ********************** RIGHT PANEL ********************** -->
    <div class="flex-grow-1">
      <h3 class="text-h6 font-weight-bold mb-2">Address</h3>
      <div>{{ driver.address }}, {{ driver.postalCode }} {{ driver.city }}</div>
    </div>

  </div>
</template>


<script setup lang="ts">

  import Avatar           from '@/assets/avatar.png'
  import StatusChip       from '../shared/StatusChip.vue';
  import type { Driver }  from '@/models'

  const props = defineProps<{
    driver: Driver
  }>()

</script>

// React/src/components/drivers/Details.tsx
import type { Driver }    from '../../models'
import { getStatusColor } from '../../utils/getStatusColor'

// ********** COMPONENTS **********
import {
  Box,
  Typography,
  Divider,
  Chip,
  Avatar,
  Stack,
}                 from '@mui/material'
import AvatarImg  from '../../assets/avatar.png'


// ********** PROPS **********
type Props = {
  driver: Driver
}


const DriverDetails = ({ driver }: Props) => {

  // ********** DATA **********
  const statusColor = getStatusColor(driver.status)

  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: { xs: 'column', sm: 'row' },
        gap: 3,
      }}
    >

      {/* ******************** LEFT PANEL ******************** */}
      <Box sx={{ display: 'flex', gap: 2, alignItems: 'center', minWidth: 250 }}>

        {/* ********** PROFILE IMAGE ********** */}
        <Avatar
          src={AvatarImg}
          alt="Driver"
          sx={{ width: 100, height: 100, borderRadius: 2 }}
        />


        {/* ********** DRIVER INFO ********** */}
        <Stack spacing={0.5}>
          <Typography variant="body2">
            <strong>Email:</strong> {driver.email}
          </Typography>
          <Typography variant="body2">
            <strong>Phone:</strong> {driver.phone}
          </Typography>
          <Box sx={{ display: 'flex', alignItems: 'center', mt: 0.5 }}>
            <strong>Status:</strong>&nbsp;
            <Chip label={driver.status} color={statusColor} size="small" />
          </Box>
        </Stack>

      </Box>


      {/* ******************** VERTICAL DIVIDER ******************** */}
      <Divider
        orientation="vertical"
        flexItem
        sx={{ display: { xs: 'none', md: 'block' } }}
      />


      {/* ******************** RIGHT PANEL ******************** */}
      <Box flex={1}>

        {/* ********** ADDRESS ********** */}
        <Typography variant="h6" fontWeight={600} gutterBottom>
          Address
        </Typography>

        <Typography>
          {driver.address}, {driver.postalCode} {driver.city}
        </Typography>

        {/* Tu peux ajouter d'autres infos ici si nécessaire */}

      </Box>

    </Box>
  )
}

export default DriverDetails
